"""Generate the graphify knowledge graph HTML for the cache integration goal."""
import json
from pathlib import Path

nodes = [
    {"id": 0, "label": "knowledge_cache.py", "group": "file", "color": "#4a90d9", "shape": "box"},
    {"id": 1, "label": "querying.py", "group": "file", "color": "#4a90d9", "shape": "box"},
    {"id": 2, "label": "index_registry.py", "group": "file", "color": "#4a90d9", "shape": "box"},
    {"id": 3, "label": "test_knowledge_cache.py", "group": "test", "color": "#27ae60", "shape": "box"},
    {"id": 4, "label": "test_engine_querying.py", "group": "test", "color": "#27ae60", "shape": "box"},
    {"id": 10, "label": "QueryResultCache", "group": "class", "color": "#e74c3c"},
    {"id": 11, "label": "_cache_key(q,provider,index)", "group": "fn", "color": "#f39c12"},
    {"id": 12, "label": "build(settings,index_id)", "group": "fn", "color": "#f39c12"},
    {"id": 13, "label": "get(question)", "group": "fn", "color": "#f39c12"},
    {"id": 14, "label": "put(question,result)", "group": "fn", "color": "#f39c12"},
    {"id": 20, "label": "RagQueryRequest", "group": "class", "color": "#9b59b6"},
    {"id": 21, "label": "RagQueryResult", "group": "class", "color": "#9b59b6"},
    {"id": 22, "label": "query_rag(req)", "group": "fn", "color": "#e67e22"},
    {"id": 23, "label": "_prepare_rag_settings(req)", "group": "fn", "color": "#e67e22"},
    {"id": 24, "label": "execute_retrieval_plan(...)", "group": "fn", "color": "#e67e22"},
    {"id": 25, "label": "knowledge_search(req)", "group": "fn", "color": "#e67e22"},
    {"id": 26, "label": "query_swarm(req)", "group": "fn", "color": "#e67e22"},
    {"id": 30, "label": "IndexManifest", "group": "class", "color": "#1abc9c"},
    {"id": 31, "label": "index_id: str", "group": "field", "color": "#16a085"},
    {"id": 32, "label": "embedding_signature\n(provider:model)", "group": "field", "color": "#16a085"},
    {"id": 40, "label": "GAP: cache never\ncalled in query_rag", "group": "gap", "color": "#c0392b", "shape": "diamond"},
]

edges = [
    {"from": 0, "to": 10}, {"from": 0, "to": 11}, {"from": 0, "to": 12},
    {"from": 0, "to": 13}, {"from": 0, "to": 14},
    {"from": 1, "to": 22}, {"from": 1, "to": 23}, {"from": 1, "to": 24},
    {"from": 1, "to": 25}, {"from": 1, "to": 26},
    {"from": 1, "to": 20}, {"from": 1, "to": 21},
    {"from": 3, "to": 10}, {"from": 4, "to": 22},
    {"from": 10, "to": 11, "label": "uses"},
    {"from": 10, "to": 12, "label": "classmethod"},
    {"from": 10, "to": 13, "label": "method"},
    {"from": 10, "to": 14, "label": "method"},
    {"from": 22, "to": 23, "label": "calls"},
    {"from": 22, "to": 24, "label": "calls"},
    {"from": 23, "to": 30, "label": "loads manifest"},
    {"from": 30, "to": 31}, {"from": 30, "to": 32},
    {"from": 12, "to": 32, "label": "SHOULD USE (currently bare provider)"},
    {"from": 22, "to": 40, "label": "missing link"},
    {"from": 40, "to": 10, "label": "should call"},
]

html_parts = [
    '<!DOCTYPE html>',
    '<html><head><meta charset="utf-8"/>',
    '<title>METIS Cache Integration Knowledge Graph</title>',
    '<script src="https://cdn.jsdelivr.net/npm/vis-network@9.1.2/dist/vis-network.min.js"></script>',
    '<link href="https://cdn.jsdelivr.net/npm/vis-network@9.1.2/dist/dist/vis-network.min.css" rel="stylesheet"/>',
    '<style>',
    'body{font-family:sans-serif;background:#1a1a2e;color:#eee;margin:0}',
    '#header{padding:16px 24px;background:#16213e;border-bottom:2px solid #e74c3c}',
    'h1{margin:0;font-size:1.3em;color:#e74c3c}',
    'p{margin:4px 0 0;font-size:.85em;color:#aaa}',
    '#graph{height:calc(100vh - 100px)}',
    '#legend{position:fixed;bottom:16px;left:16px;background:#16213e;padding:12px;border-radius:8px;font-size:.8em}',
    '.leg{display:flex;align-items:center;gap:8px;margin:4px 0}',
    '.dot{width:12px;height:12px;border-radius:50%;flex-shrink:0}',
    '</style></head><body>',
    '<div id="header">',
    '  <h1>METIS Cache Integration Knowledge Graph</h1>',
    '  <p>Goal: Wire QueryResultCache into query_rag() — easiest AutoLoop goal (5 iterations)</p>',
    '</div>',
    '<div id="graph"></div>',
    '<div id="legend">',
    '  <div class="leg"><div class="dot" style="background:#4a90d9"></div> Source file</div>',
    '  <div class="leg"><div class="dot" style="background:#27ae60"></div> Test file</div>',
    '  <div class="leg"><div class="dot" style="background:#e74c3c"></div> Class / GAP</div>',
    '  <div class="leg"><div class="dot" style="background:#f39c12"></div> Cache method</div>',
    '  <div class="leg"><div class="dot" style="background:#e67e22"></div> Query function</div>',
    '  <div class="leg"><div class="dot" style="background:#1abc9c"></div> Manifest model</div>',
    '</div>',
    '<script>',
    'const nodes = new vis.DataSet(' + json.dumps(nodes) + ');',
    'const edges = new vis.DataSet(' + json.dumps(edges) + ');',
    'const container = document.getElementById("graph");',
    'const data = {nodes, edges};',
    'const options = {',
    '  nodes:{font:{color:"#fff",size:13},borderWidth:2},',
    '  edges:{font:{color:"#bbb",size:11},arrows:{to:{enabled:true}}},',
    '  physics:{barnesHut:{gravitationalConstant:-4000,springLength:140}},',
    '  layout:{improvedLayout:true}',
    '};',
    'new vis.Network(container, data, options);',
    '</script></body></html>',
]

out = Path(__file__).parent
(out / "graph.html").write_text("\n".join(html_parts), encoding="utf-8")
print("Written:", out / "graph.html")
